### ISSUE TITLE
Change redirection from sequential to random

### ISSUE THREAD

**Issue by wilkersonp** [priyom/pavlova#2] opened 2021-05-20 03:43 UTC

**Comment by linkfanel** [comment] 2021-05-28 23:22
The receivers are listed and probed in order of preference, with the ones expected to give the best reception listed first. This is the whole point of the sequential process, by design. What would be the point or advantages that you see in random redirection?

**Comment by linkfanel** [comment] 2022-11-12 19:08
The current behavior is by design, rationale for randomization remains unclear. I'm closing this.

**Closed as not planned by linkfanel** 2022-11-12 19:08 UTC
